name: Build TIPA (TrollStore)

on:
  workflow_dispatch:

jobs:
  build-tipa:
    name: Build TrollStore .tipa
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          export PATH=/usr/local/bin:$PATH
          echo "RUNNER=1" >> $GITHUB_ENV

      - name: Install JDK 8 (Zulu)
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Export Java env
        run: |
          JDK_BASE_PATH="${{ steps.setup-java.outputs.path }}"
          echo "JAVA_HOME=$JDK_BASE_PATH" >> $GITHUB_ENV
          echo "BOOTJDK=$JDK_BASE_PATH/bin" >> $GITHUB_ENV
          echo "PATH=$JDK_BASE_PATH/bin:$PATH" >> $GITHUB_ENV

      - name: Get JRE8
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          path: depends
          workflow_conclusion: success
          allow_forks: false
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre8
          name: jre8-ios-aarch64

      - name: Get JRE17
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          path: depends
          workflow_conclusion: success
          allow_forks: false
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre17-21
          name: jre17-ios-aarch64

      - name: Get JRE21
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          path: depends
          workflow_conclusion: completed
          allow_forks: false
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre17-21
          name: jre21-ios-aarch64

      - name: Install dependencies
        run: |
          brew update || true
          brew install wget cmake || true

      - name: Build .tipa
        run: |
          set -e
          make dsym package PLATFORM=2 TROLLSTORE_JIT_ENT=1

      - name: Upload tipa artifact
        uses: actions/upload-artifact@v4
        with:
          name: amethyst-trollstore-tipa
          path: artifacts/*.tipa
